---
generic-service:
  nameOverride: san-eleventy-test

  replicaCount: 1 # we can start with one and do more

  env:
    RUNNER_LABELS: san-eleventy-test

  image:
    repository: ghcr.io/ministryofjustice/san-eleventy-test
    tag: xxx    # override at deployment time
    port: 8080
       
  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: san-eleventy-test

  # Due to a bug cant disable/override the sub chart.
  # https://github.com/helm/helm/pull/12162
  # Looks like it might be fixed, so...

  livenessProbe:
    httpGet:
      path: /

  readinessProbe:
    httpGet:
      path: /

  # livenessProbe:
  #   httpGet:
  #     path: /ping
  #     port: 8080
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   timeoutSeconds: 5
  #   failureThreshold: 5

  # readinessProbe:
  #   httpGet:
  #     path: /ping
  #     port: 8080
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   timeoutSeconds: 5
  #   failureThreshold: 5

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

imagePullSecrets: 
  - sre-doc
  #namespace_secrets:
   # santest:
    #  GITHUB_REPOSITORY: "GITHUB_REPOSITORY"
     # GITHUB_TOKEN: "GITHUB_TOKEN"

generic-prometheus-alerts:
  targetApplication: san-eleventy-test
