name: Get environment details
description: Map the GitHub environment name to the corresponding Namespace environment details

inputs:
  environment:
    description: GitHub environment name
    required: true

outputs:
  values-file:
    description: The filename for the values file containing environment configuration
    value: ${{ steps.cloud-platform.outputs.values-file }}
  cloud-platform-namespace:
    description: The name of the corresponding Cloud Platform namespace
    value: ${{ steps.cloud-platform.outputs.namespace }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Map GitHub environment to Cloud Platform namespace
      id: cloud-platform
      shell: bash
      run: |
        if [ '${{ inputs.environment }}' == 'development' ];    then namespace='dev'; fi
        echo "namespace=${namespace}" | tee -a "$GITHUB_OUTPUT"
        echo "values-file=values-${namespace}.yaml" | tee -a "$GITHUB_OUTPUT"
