name: Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

jobs:

  test_docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/create_app_version.yml@feat/HEAT-344-create-deploy_env_workflow
