name: Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

jobs:

  test_docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/create_app_version.yml@feat/HEAT-344-create-deploy_env_workflow
    secrets: inherit
    with:
      docker_registry: ${{ inputs.docker_registry || 'ghcr.io' }}
      registry_org: ${{ inputs.registry_org || 'ministryofjustice' }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: ${{ inputs.docker_multiplatform || false }}
