name: Deploy

on:
  workflow_call:
    inputs:      
      environment:
        description: The name of the environment to deploy to (dev/prod)
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    environment:
      name: ${{ inputs.environment }}  
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-env-details
        id: env
        with:
          environment: ${{ inputs.environment }}

      - name: Deploy to Platform
        uses: ./.github/actions/cloud-platform-deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}    
