name: Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true      

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      push: true
    secrets: inherit
