name: Pipeline

on:
  push:
    branches:
      - main

on:
  workflow_dispatch:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        default: 'ghcr.io'
        type: choice
        options:
          - 'ghcr.io'
          - 'quay.io'
      registry_org:
        description: Docker registry organisation
        required: true
        default: 'ministryofjustice'
        type: choice
        options:
          - 'ministryofjustice'
          - 'hmpps'
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: 'true'
        type: boolean
        
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false

jobs:
  build_test_node:
    name: Build node
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build_test.yml@HEAT-353-typescript-node-workflow
    secrets: inherit
  test_docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_docker_build.yml@feat/HEAT-354-docker-build
    secrets: inherit
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push}}
